image: "registry.gitlab.com/dmfigol/base-docker-images/python:3.6-slim-stretch"

stages:
  - test
  - publish

before_script:
  - /root/.poetry/bin/poetry install --no-interaction

test:
  stage: test
  script:
    - .venv/bin/black --check simple_smartsheet examples tests
    - .venv/bin/flake8 simple_smartsheet examples tests
    - .venv/bin/mypy simple_smartsheet
    - .venv/bin/pytest --record-mode=all
    - .venv/bin/python -Werror examples/sheets.py > /dev/null
    - .venv/bin/python -Werror examples/report.py > /dev/null
    - .venv/bin/python -Werror examples/custom_indexes.py > /dev/null
    - .venv/bin/python -Werror examples/async.py > /dev/null
  tags:
    - docker
  except:
    - master


publish:
  stage: publish
  script:
    - /root/.poetry/bin/poetry publish --build -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
  tags:
    - docker
  only:
    - tags
