image: "registry.gitlab.com/dmfigol/base-docker-images/python:3.6-slim-stretch"

stages:
  - test
  - publish

before_script:
  - /root/.poetry/bin/poetry install --no-interaction

test:
  stage: test
  script:
    - .venv/bin/black --check simple_smartsheet
    - .venv/bin/mypy simple_smartsheet
    - .venv/bin/flake8 simple_smartsheet
  tags:
    - docker


publish:
  stage: publish
  script:
    - /root/.poetry/bin/poetry publish --build -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
  tags:
    - docker
  only:
    - tags
