version: '2'

tasks:
  install:
    cmds:
      - poetry install -E pandas

  publish:
    cmds:
      - poetry publish --build -u __token__ -p ${PYPI_TOKEN}

  black:
    cmds:
      - poetry run black simple_smartsheet examples tests

  black-check:
    cmds:
      - poetry run black --check simple_smartsheet examples tests

  flake8:
    cmds:
      - poetry run flake8 simple_smartsheet examples tests

  mypy:
    cmds:
      - poetry run mypy simple_smartsheet

  test-precheck:
    cmds:
      - task: black-check
      - task: flake8
      - task: mypy

  pytest-prod:
    cmds:
      - poetry run pytest tests/prod -rf

  pytest-local:
    cmds:
      - poetry run pytest tests/sandbox --record-mode=none --block-network -rf

# new_episodes does not work as expected and async tests just crash
#  pytest-record-new:
#    cmds:
#      - poetry run pytest tests/sandbox --record-mode=new_episodes -rf

  pytest-rerecord:
    cmds:
      - poetry run pytest tests/sandbox --record-mode=all --delete-cassettes -rf

  pytest-novcr:
    cmds:
      - poetry run pytest tests/sandbox --disable-vcr -rf

  examples:
    cmds:
      - poetry run python -Werror examples/sheets.py > /dev/null
      - poetry run python -Werror examples/report.py > /dev/null
      - poetry run python -Werror examples/custom_indexes.py > /dev/null
      - poetry run python -Werror examples/async.py > /dev/null

  tests-local:
    cmds:
      - task: test-precheck
      - task: pytest-local

  tests:
    cmds:
      - task: test-precheck
      - task: pytest-local
      - task: examples

  tests-novcr:
    cmds:
      - task: test-precheck
      - task: pytest-novcr
      - task: examples
