on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/dmfigol/base-docker-images/python:3.6-slim-buster
    env:
      SIMPLE_SMARTSHEET_STRICT_VALIDATION: "1"
    steps:
    - uses: actions/checkout@v2
    - name: Running tests
      run: |
        poetry install --no-interaction
        task tests
