on: release
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/dmfigol/base-docker-images/python:3.6-slim-buster
    env:
      SIMPLE_SMARTSHEET_STRICT_VALIDATION: "1"
      SMARTSHEET_API_TOKEN: ${{ secrets.SMARTSHEET_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Running tests
      run: |
        poetry install --no-interaction
        task tests-record

  publish:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/dmfigol/base-docker-images/python:3.6-slim-buster
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Publish to PyPi
      run: poetry publish --build -u __token__ -p ${PYPI_TOKEN}
